### ISSUE TITLE
Loki naming in Default file locations, Win Install

### ISSUE THREAD

**Issue by flash25296** [oxen-io/oxen-electron-gui-wallet#260]
With the rebrand to Oxen, the new Oxen wallet still used default LOKI storage locations when installing the wallet.

Data Storage Path = C:\ProgramData\loki
Wallet Storage Path = C:\Users\xxxxxx\Documents\Loki

Key Image Export Directory = C:/users/xxxxxx/Documents/Loki/image/WalletName

It would be nice to clean these up and remove the Loki shadow from Oxen rebrand

**Comment by darcys22** [comment]
The default logic now is to check if a "Loki" path exists, if true then use it. Otherwise create an "Oxen" path. 

Over time this will naturally transition people over to "Oxen" without causing breaking changes to users. The concern is more on backwards compatibility for the time being.

After some reasonably long transition period we will likely remove the "loki" path search entirely. But for the time being this is functioning as intended
