### ISSUE TITLE
"Starting daemon" takes ages

### ISSUE THREAD

**Issue by 144** [oxen-io/oxen-electron-gui-wallet#286]
"Starting daemon" with full node takes age to run. Would be nice if you guys optimized it somehow, I'm waiting over 30 minutes now and its still stuck at "Starting daemon".

Windows 10
v1.6.0

**Comment by darcys22** [comment]
To run a full node means syncing the blockchain from scratch which takes time. I personally leave a node to sync for a full day before even checking if the sync finished.

There isn't really much we can do to optimise this, there are options a user can take such as downloading the full chain from a trusted source to speed this up. But this makes the blockchain sync centralised rather than decentralised so its unlikely to be included as the default option.

Closing with no further action. If you would like to further discuss how to do the above please reach out on our community channels (Telegram/Discord) and we can assist.
